const { withAppBuildGradle } = require("@expo/config-plugins");

/**
 * Config plugin that appends a release signing configuration block to the
 * generated android/app/build.gradle file.
 *
 * Instead of trying to find and modify the existing signingConfigs/buildTypes
 * blocks (which is fragile and breaks when the generated structure changes),
 * we simply APPEND a new `android {}` block at the end of the file.
 *
 * Gradle allows the `android {}` block to be configured multiple times, so the
 * appended block re-declares `signingConfigs.release` and sets
 * `buildTypes.release.signingConfig` to use it — overriding whatever was
 * generated by prebuild. This works regardless of the generated structure.
 *
 * Credentials are read from environment variables at build time, so no secrets
 * are stored in the repository.
 */
module.exports = function withAndroidSigning(config) {
  return withAppBuildGradle(config, (modConfig) => {
    const signingBlock = `
android {
    signingConfigs {
        release {
            storeFile file(System.getenv("RELEASE_STORE_FILE") ?: "release-keystore.jks")
            storePassword System.getenv("RELEASE_STORE_PASSWORD")
            keyAlias System.getenv("RELEASE_KEY_ALIAS")
            keyPassword System.getenv("RELEASE_KEY_PASSWORD")
            storeType "PKCS12"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
`;

    // Only append if the block isn't already present (idempotent)
    if (!modConfig.modResults.contents.includes("signingConfigs.release")) {
      modConfig.modResults.contents += signingBlock;
    }

    return modConfig;
  });
};
